# Generated by Django 5.1.3 on 2025-02-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antonyme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200, unique=True)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('non', 'Non'), ('vèb', 'Vèb'), ('adjektif', 'Adjektif'), ('advèb', 'Advèb'), ('ekspresyon', 'Ekspresyon')], max_length=20)),
                ('description', models.TextField()),
                ('exemple', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyme', models.CharField(max_length=100)),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinonim', to='home.mot')),
            ],
        ),
        migrations.DeleteModel(
            name='DictionaryEntry',
        ),
        migrations.AddField(
            model_name='antonyme',
            name='mot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonim', to='home.mot'),
        ),
    ]
